# Computational Mathematics  <a class="tocSkip">

## More linear algebra and its applications <a class="tocSkip">
    
### Homework Exercises <a class="tocSkip">

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Homework" data-toc-modified-id="Homework-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Homework</a></span><ul class="toc-item"><li><span><a href="#Homework---Fibonacci-matrix" data-toc-modified-id="Homework---Fibonacci-matrix-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Homework - Fibonacci matrix</a></span></li><li><span><a href="#Homework---Transformation-using-the-diagonalisation-matrices-in-turn---a-symmetric-example" data-toc-modified-id="Homework---Transformation-using-the-diagonalisation-matrices-in-turn---a-symmetric-example-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Homework - Transformation using the diagonalisation matrices in turn - a symmetric example</a></span></li><li><span><a href="#Homework---SVD-example" data-toc-modified-id="Homework---SVD-example-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Homework - SVD example</a></span><ul class="toc-item"><li><span><a href="#Warning" data-toc-modified-id="Warning-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Warning</a></span></li></ul></li><li><span><a href="#Homework---Transformation-due-to-multiplication-by-a-non-square-matrix---SVD-interpretation" data-toc-modified-id="Homework---Transformation-due-to-multiplication-by-a-non-square-matrix---SVD-interpretation-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Homework - Transformation due to multiplication by a non-square matrix - SVD interpretation</a></span></li><li><span><a href="#Homework---When-does-the-SVD-agree-with-the-eigen-decomposition?" data-toc-modified-id="Homework---When-does-the-SVD-agree-with-the-eigen-decomposition?-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Homework - When does the SVD agree with the eigen-decomposition?</a></span></li><li><span><a href="#Homework-$2\times-2$-ODE-example-from-class" data-toc-modified-id="Homework-$2\times-2$-ODE-example-from-class-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Homework $2\times 2$ ODE example from class</a></span></li><li><span><a href="#Homework---eigenvalues-of-the-MSD-system" data-toc-modified-id="Homework---eigenvalues-of-the-MSD-system-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Homework - eigenvalues of the MSD system</a></span></li><li><span><a href="#Homework---eigenvectors-of-the-MSD-system-[**]" data-toc-modified-id="Homework---eigenvectors-of-the-MSD-system-[**]-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Homework - eigenvectors of the MSD system [**]</a></span></li><li><span><a href="#Homework---stability-of-forward-Euler-applied-to-the-MSD-problem" data-toc-modified-id="Homework---stability-of-forward-Euler-applied-to-the-MSD-problem-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Homework - stability of forward Euler applied to the MSD problem</a></span></li><li><span><a href="#Homework---the-double-pendulum-[*]" data-toc-modified-id="Homework---the-double-pendulum-[*]-1.10"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>Homework - the double pendulum [*]</a></span></li><li><span><a href="#Homework---the-triple-pendulum-[*]" data-toc-modified-id="Homework---the-triple-pendulum-[*]-1.11"><span class="toc-item-num">1.11&nbsp;&nbsp;</span>Homework - the triple pendulum [*]</a></span></li></ul></li></ul></div>

In [1]:
%matplotlib inline
%precision 4
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as sl
from pprint import pprint
from mpl_toolkits.mplot3d import Axes3D

In [2]:
%%html
<style>
div.optional {
    display: block;
    background-color: #d7e2ff;
    border-color: #d7e2ff;
    border-left: 5px solid #d7e2ff;
    padding: 0.5em;
}
div.advanced {
    display: block;
    background-color: #fff4d7;
    border-color: #fff4d7;
    border-left: 5px solid #fff4d7;
    padding: 0.5em;
}
</style>

# Homework

## Homework - Fibonacci matrix

The Fibonacci matrix is defined as

$$Q = \begin{pmatrix}
1 & 1\\
1 & 0
\end{pmatrix}$$

Compute by hand the eigenvalues and eigenvectors of the $Q$ matrix.

Check numerically that you can use these to form a diagonalization of $Q$.

We will make use of this matrix and its diagonalisation in lecture 4.

In [3]:
Q = np.array([[1., 1.], [1.,0.]])
lam1 = (1+np.sqrt(5))/2
lam2 = (1-np.sqrt(5))/2
v1 = np.array([lam1, 1.])
v2 = np.array([lam2, 1.])

# force v1 and v2 to be column vecs
v1.shape = (2,1)
v2.shape = (2,1)

# and stack them into the matrix P
P = np.hstack((v1,v2))
# and form the diagonal matrix with e'vals on the main diagonal
Lambda = np.diag(np.array([lam1,lam2]))

# we can check if our result is (approximately - read the docs) correct with
print('Q = P \Lambda P^{-1}:  ', np.allclose(Q , P@Lambda@(sl.inv(P))))

Q = P \Lambda P^{-1}:   True


## Homework - Transformation using the diagonalisation matrices in turn - a symmetric example

Please read through the section of the lecture notes titled "Please read through the section of the lecture notes titled".

Repeat the steps 

\begin{align*}
A\boldsymbol{x} = P \Lambda P^{-1}\boldsymbol{x} = P \; (\Lambda\;  (P^{-1}\boldsymbol{x}))
\end{align*}

geometrically starting for a unit circle using the symmetric matrix 

$$ A = 
\left(
  \begin{array}{rr}
    3.6 & 1.6 \\
    1.6 & 3.2  
  \end{array}
\right)
$$



Confirm what was said in the lecture that the $P$ and thus $P^{-1}$ being orthogonal matrices means that they just correspond to simple rotations.

NB. you can just use `sl.eig` to find the eigenvalues and eigenvectors.

In [ ]:
A = np.array([[3.6,1.6],[1.6,3.2]])


## Homework - SVD example

Consider the $3\times 4$ (i.e. non-square) matrix

$$A = \begin{pmatrix} 
3 & 1 & 9 & 4 \\
2 & 1 & 7 & 3 \\
5 & 2 & 16 & 7 
\end{pmatrix}$$

Check that 

$$A = U\Sigma V^{T}$$

using the definitions of the RHS matrices in terms of eigenvalues and eigenvectors of $AA^T$ and $A^TA$.

<br>

### Warning
Note that we need to choose the signs of our left and right singular vectors consistently - an issue arises if we compute these as the eigenvectors of  $AA^T$ and $A^TA$ separately. If you get an SVD that doesn't result in $A$ it might well be that you have a sign inconsistency, for more on this see: 

- <https://math.stackexchange.com/questions/2359992/how-to-resolve-the-sign-issue-in-a-svd-problem>.

You can check the signs of your columns of $U$ and $V$ against the SciPy solution, and if needed flip the signs of he appropriate columns.

<br>

This issue appears again in Lecture 6 (Probability & ML) in the context of going through a PCA example in detail.


In [10]:
A = np.array([
    [3,1,9,4],
    [2,1,7,3],
    [5,2,16,7]])
UU,SS,VVT = sl.svd(A)
SSS = np.zeros_like(A,dtype='float')
SSS[:min(A.shape[0], A.shape[1]), :min(A.shape[0],A.shape[1])] = np.diag(SS)

print('\nSS',SS)
print('UU',UU)
print('VV',VVT.T)
print('SSS',SSS)
print('res', UU@SSS@VVT)



SS [2.2448e+01 3.1814e-01 9.3467e-16]
UU [[-0.4607 -0.6741 -0.5774]
 [-0.3534  0.736  -0.5774]
 [-0.8141  0.0619  0.5774]]
VV [[-0.2744 -0.7561  0.5866  0.0939]
 [-0.1088  0.584   0.6199  0.5127]
 [-0.8752  0.2398 -0.0332 -0.4188]
 [-0.3832 -0.1721 -0.5201  0.7436]]
SSS [[2.2448e+01 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 3.1814e-01 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 9.3467e-16 0.0000e+00]]
res [[ 3.  1.  9.  4.]
 [ 2.  1.  7.  3.]
 [ 5.  2. 16.  7.]]


In [27]:
A = np.array([
    [3,1,9,4],
    [2,1,7,3],
    [5,2,16,7]])
U = sl.eig(A@A.T)[1]
print('U:',U)
V = sl.eig(A.T@A)[1]
print('V',V)
eigs1 = np.real(sl.eig(A@A.T)[0])
print(eigs1)
eigs2 = np.real(sl.eig(A.T@A)[0])
print(eigs2)
sigma = np.zeros_like(A,dtype='float')
sigma[:min(A.shape[0],A.shape[1]),:min(A.shape[0],A.shape[1])] = np.diag(np.sqrt(eigs1))
print('sigma:',sigma)
print('res', U@(sigma@V.T))
U[:,1] = -U[:,1]
pprint(U@(sigma@V.T))


U: [[-0.4607 -0.6741 -0.5774]
 [-0.3534  0.736  -0.5774]
 [-0.8141  0.0619  0.5774]]
V [[-0.2744  0.7561  0.3902 -0.3086]
 [-0.1088 -0.584   0.7631 -0.0112]
 [-0.8752 -0.2398 -0.3729 -0.2974]
 [-0.3832  0.1721  0.3555  0.9034]]
[5.0390e+02 1.0121e-01 2.7798e-14]
[ 5.0390e+02  1.0121e-01  4.4997e-15 -1.1239e-15]
sigma: [[2.2448e+01 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 3.1814e-01 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 1.6673e-07 0.0000e+00]]
res [[ 2.6757  1.2505  9.1029  3.9262]
 [ 2.3541  0.7265  6.8877  3.0806]
 [ 5.0298  1.977  15.9905  7.0068]]
array([[ 3.,  1.,  9.,  4.],
       [ 2.,  1.,  7.,  3.],
       [ 5.,  2., 16.,  7.]])


## Homework - Transformation due to multiplication by a non-square matrix - SVD interpretation

Consider the following matrix as an example of an over-determined problem

$$
  \begin{pmatrix}
    2 & 3 \\
    1 & -4  \\
    -3 & -10 
  \end{pmatrix}
$$

This matrix maps $\mathbb{R}^2$ into $\mathbb{R}^3$.

As was done above for a square $2\times 2$ case, visualise each three multiplications by the matrices making up the SVD acting in the unit circle

In [ ]:
A = np.array([[2,3],[1,-4],[-3,-10]])
UU,SS,VVT = sl.svd(A)


## Homework - When does the SVD agree with the eigen-decomposition?

Consider a square matrix - check whether the SVD and the eigen-decompositions agree. 

Compare the cases of a symmetric matrix and a non-symmetrix matrix.

## Homework $2\times 2$ ODE example from class

From the lecture consider the $2\times 2$ problem


$$\dot{\boldsymbol{x}}(t) = A\boldsymbol{x}$$

where

$$\boldsymbol{x}(t) = 
\begin{pmatrix}
x_1(t)\\
x_2(t)
\end{pmatrix}$$

and 

$$A = 
\begin{pmatrix}
-1 & 3 \\
3 & -1
\end{pmatrix}
$$

Show that the solution is given by

\begin{align*}
\boldsymbol{x}(t) &= \exp(tA) \boldsymbol{C}
 = \frac{1}{2}(C_1+C_2)
\begin{pmatrix}
1 \\
1
\end{pmatrix}\exp(2t)+
\frac{1}{2}(C_2-C_1)
\begin{pmatrix}
-1 \\
1
\end{pmatrix}\exp(-4t)
\end{align*}

Hint: You will need to start by the eigenvalues and eigenvectors of $A$.

For the case with initial condition


$$\boldsymbol{x}(0)=
\begin{pmatrix}
0.1 \\
0
\end{pmatrix}
$$

compute and plot the exact solution as well as a numerical solution using forward Euler over the interval $t\in[0,1]$.

You should find that the solution(s) tend(s) to $\pm$ infinity for large times, depending on the signs of the initial conditions.

Looking at the form of the solution, what initial conditions lead to a solution which tends to zero as time increases? Does the numerical solution agree with this qualitative behaviour (especially in the case of selecting too large a time step size)?

## Homework - eigenvalues of the MSD system

Find the eigenvalues of the matrix that corresponds to the MSD matrix from the lecture:

$$
\begin{pmatrix}
0 & 1\\
-\omega_0^2 & -2\zeta\omega_0
\end{pmatrix}.$$

<div class="advanced">

## Homework - eigenvectors of the MSD system [**]

Work out expressions for the eigenvectors of the system.
    
</div>

## Homework - stability of forward Euler applied to the MSD problem

We're going to implement and test a solver for the general system of ODEs in the form

$$\frac{d\boldsymbol{y}}{dt} = f(\boldsymbol{y})$$

and test it using the MSD problem from the lecture.

In this case we can write a function for the RHS function in the form

```Python
def f_msd(t, u):
    """RHS function for mass-spring-damper problem.

    Parameters
    ----------
    t : array_like
        Array containing the current timestep
    u : array_like
        For MSD u is the vector [x, v]

    Returns
    -------
    f : ndarray
        RHS function value
    """
    f = np.zeros_like(u)
    f[0] = u[1]
    f[1] = -2.*zeta*om0*u[1] - om0**2 * u[0]
# NB. could write this as A*u with
# A = np.matrix([[0, 1], [-om0**2, -2*zeta*om0]])
    return f
```

Implement a forward Euler time-stepping function and test it against the implementation from the lecture.

Hint:  your solution might look something like (you need to fill in some gaps):

```Python
def forward_euler(f, u0, t0, t_max, dt):
    """ Forward Euler time-stepper.

    Parameters
    ----------
    f : callable
        f(t,y) is the RHS function
    u0 : array_like
        The initial condition
    t0 : float
        The initial time
    t_max : float
        The end time
    dt : float
        Time step size.

    Returns
    -------
    tuple of ndarray
        Tuple containing ndarrays with all u and t values
    """
    u = np.array(u0)
    t = np.array(t0)
    u_all = [u0]
    t_all = [t0]
    while t < t_max:
        u = ........
        u_all.append(u)
        t = ........
        t_all.append(t)
    return np.array(u_all), np.array(t_all)
```


Consider the following physical and numerical parameters

$$\omega_0=1,\quad x_0=1,\quad v_0=0, \quad t_0=0, \quad t_f=20 $$

To finish off the selection of parameters consider three cases:


1. $$\Delta t = 0.05, \quad \zeta = 0.05$$


2. $$\Delta t = 0.2, \quad \zeta = 0.05$$


3. $$\Delta t = 0.2, \quad \zeta = 0.2$$


What qualitative difference in solutions do you observe in the three cases?


<div class="optional">
    
## Homework - the double pendulum [*]

Take a look at <https://en.wikipedia.org/wiki/Double_pendulum>

<img src="./figures/1000px-Double-compound-pendulum-dimensioned.svg.png" width=300x>

Image: <https://commons.wikimedia.org/wiki/File:Double-compound-pendulum-dimensioned.svg>

Note that the equations listed in this Wikipedia page are in terms of coordinates (actually the angles) giving the midpoints of assumed unit length rods - other places you look may have these lengths (and the masses at the ends of the rods) flexible and the equations be in terms of coordinates giving the actual locations of the ends of the rods - they should all ultimately give the same answer!

See if you can formulate the problem using the coupled ODEs described on this page (for the derivatives of $\theta_1$, $\theta_2$, $p_{\theta_1}$ and $p_{\theta_2}$ - don't worry too much what these latter two quantities are physically).

You can attempt with forward Euler, but I suggest you use `scipy.integrate.solve_ivp` like we did for the more complex examples in the lecture.

Note that to plot correctly, depending on how you go about things, you may need to think about how to turn the two angles into appropriate $x$ and $y$ coordinates.
    
</div>

<div class="optional">

## Homework - the triple pendulum [*]

Take a look at this video

<http://i.imgur.com/r6FZfxr.gifv>

and the discussion here
<https://www.reddit.com/r/mathpics/comments/4nd5h1/41_triple_pendulums_with_very_slightly_different/>

and for a Python implmentation of a system of $n$ coupled pendula - using [Kane's method](https://docs.sympy.org/dev/modules/physics/mechanics/kane.html) take a look through the supplemental notebook in this directory.
    
</div>